// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include<iostream>

using namespace std;

int main() {
	int a = 0, b = 1, i = 2;
	int	sum = a, fib;
	while (i < 10) {
		fib = a + b;
		if (fib % 2 == 0)
			sum += fib;
		a = b;
		b = fib;
		i++;
	}
	cout << sum;
	return 0;
}